//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelperPerson
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateExpireNDT { get; set; }
        public Nullable<int> RemainNDT { get; set; }
        public Nullable<int> RemainMedical { get; set; }
        public Nullable<int> RemainCAO { get; set; }
        public Nullable<int> RemainPassport { get; set; }
        public Nullable<int> RemainLicence { get; set; }
        public Nullable<int> RemainSimulator { get; set; }
        public Nullable<int> RemainLanguageCourse { get; set; }
        public Nullable<int> RemainProficiency { get; set; }
        public Nullable<int> RemainCMC { get; set; }
        public Nullable<int> RemainSEPT { get; set; }
        public Nullable<int> RemainLPR { get; set; }
        public Nullable<int> RemainDG { get; set; }
        public Nullable<int> RemainCRM { get; set; }
        public Nullable<int> RemainCCRM { get; set; }
        public Nullable<int> RemainSMS { get; set; }
        public Nullable<int> RemainAvSec { get; set; }
        public Nullable<int> RemainUpsetRecoveryTraining { get; set; }
        public Nullable<int> RemainColdWeather { get; set; }
        public Nullable<int> RemainHotWeather { get; set; }
        public Nullable<int> RemainSEPTP { get; set; }
        public Nullable<int> RemainFirstAid { get; set; }
        public Nullable<int> RemainLicenceIR { get; set; }
        public Nullable<int> RemainProficiencyOPC { get; set; }
        public Nullable<int> RemainLine { get; set; }
        public Nullable<int> RemainRecurrent { get; set; }
        public Nullable<int> RemainTRI { get; set; }
        public Nullable<int> RemainTRE { get; set; }
        public Nullable<int> RemainEGPWS { get; set; }
        public Nullable<int> RemainTypeMD { get; set; }
        public Nullable<int> RemainType737 { get; set; }
        public Nullable<int> RemainTypeAirbus { get; set; }
        public Nullable<int> RemainHF { get; set; }
        public Nullable<int> RemainASD { get; set; }
        public Nullable<int> RemainGOM { get; set; }
        public Nullable<int> RemainASF { get; set; }
        public Nullable<int> RemainCC { get; set; }
        public Nullable<int> RemainERP { get; set; }
        public Nullable<int> RemainMB { get; set; }
        public Nullable<int> RemainPS { get; set; }
        public Nullable<int> RemainANNEX { get; set; }
        public Nullable<int> RemainDRM { get; set; }
        public Nullable<int> RemainFMTD { get; set; }
        public Nullable<int> RemainMEL { get; set; }
        public Nullable<int> RemainMET { get; set; }
        public Nullable<int> RemainPER { get; set; }
        public Nullable<int> RemainRSP { get; set; }
        public Nullable<int> RemainLRC { get; set; }
        public Nullable<int> RemainLPCC1 { get; set; }
        public Nullable<int> RemainLPCC2 { get; set; }
        public Nullable<int> RemainLPCC3 { get; set; }
        public Nullable<int> RemainLineC1 { get; set; }
        public Nullable<int> RemainLineC2 { get; set; }
        public Nullable<int> RemainLineC3 { get; set; }
        public Nullable<int> RemainRamp { get; set; }
        public Nullable<int> RemainAC { get; set; }
        public Nullable<int> RemainUPRT { get; set; }
        public Nullable<int> RemainSFI { get; set; }
        public Nullable<int> RemainSFE { get; set; }
        public Nullable<int> RemainTRI2 { get; set; }
        public Nullable<int> RemainTRE2 { get; set; }
        public Nullable<int> RemainIRI { get; set; }
        public Nullable<int> RemainIRE { get; set; }
        public Nullable<int> RemainCRI { get; set; }
        public Nullable<int> RemainCRE { get; set; }
        public Nullable<int> RemainSFI2 { get; set; }
        public Nullable<int> RemainSFE2 { get; set; }
        public Nullable<int> RemainAirCrew { get; set; }
        public Nullable<int> RemainAirOps { get; set; }
        public Nullable<int> RemainSOP { get; set; }
        public Nullable<int> RemainDiff31 { get; set; }
        public Nullable<int> RemainDiff34 { get; set; }
        public Nullable<int> RemainOMA1 { get; set; }
        public Nullable<int> RemainOMB1 { get; set; }
        public Nullable<int> RemainOMC1 { get; set; }
        public Nullable<int> RemainOMA2 { get; set; }
        public Nullable<int> RemainOMB2 { get; set; }
        public Nullable<int> RemainOMC2 { get; set; }
        public Nullable<int> RemainOMA3 { get; set; }
        public Nullable<int> RemainOMB3 { get; set; }
        public Nullable<int> RemainOMC3 { get; set; }
        public Nullable<int> RemainMap { get; set; }
        public Nullable<int> RemainComRes { get; set; }
        public Nullable<int> RemainOPCC1 { get; set; }
        public Nullable<int> RemainOPCC2 { get; set; }
        public Nullable<int> RemainOPCC3 { get; set; }
        public Nullable<int> Remain1 { get; set; }
        public Nullable<int> Remain2 { get; set; }
        public Nullable<int> Remain3 { get; set; }
        public Nullable<int> Remain4 { get; set; }
        public Nullable<int> Remain5 { get; set; }
        public Nullable<int> Remain6 { get; set; }
        public Nullable<int> Remain7 { get; set; }
        public Nullable<int> Remain8 { get; set; }
        public Nullable<int> Remain9 { get; set; }
        public Nullable<int> Remain10 { get; set; }
        public Nullable<int> Remain11 { get; set; }
        public Nullable<int> Remain12 { get; set; }
        public Nullable<int> Remain13 { get; set; }
        public Nullable<int> Remain14 { get; set; }
        public Nullable<int> Remain15 { get; set; }
        public Nullable<int> Remain16 { get; set; }
        public Nullable<int> Remain17 { get; set; }
        public Nullable<int> Remain18 { get; set; }
        public Nullable<int> Remain19 { get; set; }
        public Nullable<int> Remain20 { get; set; }
        public Nullable<int> Remain21 { get; set; }
        public Nullable<int> Remain22 { get; set; }
        public Nullable<int> Remain23 { get; set; }
        public Nullable<int> Remain24 { get; set; }
        public Nullable<int> Remain25 { get; set; }
        public Nullable<int> Remain26 { get; set; }
        public Nullable<int> Remain27 { get; set; }
        public Nullable<int> Remain28 { get; set; }
        public Nullable<int> Remain29 { get; set; }
        public Nullable<int> Remain30 { get; set; }
        public Nullable<int> Remain31 { get; set; }
        public Nullable<int> Remain32 { get; set; }
        public Nullable<int> Remain33 { get; set; }
        public Nullable<int> Remain34 { get; set; }
        public Nullable<int> Remain35 { get; set; }
        public Nullable<int> RemainTRG02 { get; set; }
        public Nullable<int> Remain36 { get; set; }
        public Nullable<int> Remain37 { get; set; }
        public Nullable<int> Remain38 { get; set; }
        public Nullable<int> Remain39 { get; set; }
        public Nullable<int> Remain40 { get; set; }
        public Nullable<int> Remain41 { get; set; }
        public Nullable<int> Remain42 { get; set; }
        public Nullable<int> Remain43 { get; set; }
        public Nullable<int> Remain44 { get; set; }
        public Nullable<int> Remain45 { get; set; }
        public Nullable<int> Remain46 { get; set; }
        public Nullable<int> Remain47 { get; set; }
        public Nullable<int> Remain48 { get; set; }
        public Nullable<int> Remain49 { get; set; }
        public Nullable<int> Remain50 { get; set; }
        public Nullable<int> RemainRIGHT_SEAT_QUALIFICATION { get; set; }
        public Nullable<int> RemainELT { get; set; }
        public Nullable<int> RemainRVSM { get; set; }
        public Nullable<int> RemainPILOT_INCAPACITATION { get; set; }
        public Nullable<int> RemainEFB { get; set; }
        public Nullable<int> RemainSafetyPilot { get; set; }
        public Nullable<int> RemainRouteCheck { get; set; }
        public Nullable<int> RemainPROFICIENCY_ASSESSMENT { get; set; }
        public Nullable<int> RemainMP { get; set; }
        public Nullable<int> RemainCALR { get; set; }
        public Nullable<int> RemainSpecialApproval { get; set; }
        public Nullable<int> RemainTRG01 { get; set; }
        public Nullable<int> RemainTRG16 { get; set; }
        public Nullable<int> RemainLOAD_CONTROL { get; set; }
        public Nullable<int> RemainPhase1 { get; set; }
        public Nullable<int> RemainPhase2 { get; set; }
        public Nullable<int> RemainPhase3 { get; set; }
        public Nullable<int> RemainGround { get; set; }
        public Nullable<int> RemainFirstAidCockpit { get; set; }
    }
}
