//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLegCrew
    {
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public int FDPId { get; set; }
        public int FDPItemId { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int GroupOrder { get; set; }
        public int IsCockpit { get; set; }
        public Nullable<int> FlightPlanId { get; set; }
        public Nullable<byte> BlockM { get; set; }
        public Nullable<int> BlockH { get; set; }
        public Nullable<int> FlightH { get; set; }
        public Nullable<byte> FlightM { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<int> Duty { get; set; }
        public Nullable<int> ScheduledFlightTime { get; set; }
        public Nullable<int> SITATime { get; set; }
        public int FixTime { get; set; }
        public Nullable<int> FlightTimeActual { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<int> FPFlightMM { get; set; }
        public Nullable<int> FPFlightHH { get; set; }
        public string OToAirportIATA { get; set; }
        public Nullable<int> OToAirportId { get; set; }
        public Nullable<System.DateTime> OSTA { get; set; }
        public Nullable<decimal> ActualFlightMTakeoff { get; set; }
        public Nullable<int> ActualFlightHTakeoff { get; set; }
        public Nullable<decimal> ActualFlightMOffBlock { get; set; }
        public Nullable<int> ActualFlightHOffBlock { get; set; }
        public Nullable<int> IsDelayLanding { get; set; }
        public Nullable<int> IsDelayOnBlock { get; set; }
        public Nullable<int> IsDelayTakeoff { get; set; }
        public Nullable<int> IsDelayOffBlock { get; set; }
        public Nullable<int> DelayLanding { get; set; }
        public Nullable<int> DelayOnBlock { get; set; }
        public Nullable<int> DelayTakeoff { get; set; }
        public Nullable<int> DelayOffBlock { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public string ArrivalRemark { get; set; }
        public string FlightStatus { get; set; }
        public string Register { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> MSN { get; set; }
        public string DepartureRemark { get; set; }
        public string FromAirportIATA { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string FlightPlan { get; set; }
        public Nullable<int> FlightMPlanned { get; set; }
        public Nullable<int> FlightHPlanned { get; set; }
        public Nullable<System.DateTime> STDPlanned { get; set; }
        public Nullable<System.DateTime> STAPlanned { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> ChocksInLocal { get; set; }
        public Nullable<System.DateTime> ChocksOutLocal { get; set; }
        public Nullable<System.DateTime> LandingLocal { get; set; }
        public Nullable<System.DateTime> TakeOffLocal { get; set; }
        public Nullable<System.DateTime> JL_OffBlock { get; set; }
        public Nullable<System.DateTime> JL_OnBlock { get; set; }
        public Nullable<System.DateTime> JL_TakeOff { get; set; }
        public Nullable<System.DateTime> JL_Landing { get; set; }
        public Nullable<System.DateTime> JL_OffBlockLocal { get; set; }
        public Nullable<System.DateTime> JL_OnBlockLocal { get; set; }
        public Nullable<System.DateTime> JL_TakeOffLocal { get; set; }
        public Nullable<System.DateTime> JL_LandingLocal { get; set; }
        public Nullable<int> JL_FlightTime { get; set; }
        public Nullable<int> JL_BlockTime { get; set; }
    }
}
