//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSyllabu
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string SessionKey { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> InstructorId { get; set; }
        public Nullable<int> InstructorId2 { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DurationActual { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public string Instructor2 { get; set; }
        public string Instructor { get; set; }
    }
}
